### ISSUE TITLE
Parameter setting

### ISSUE THREAD

**Issue by Kerry0123** [yanggeng1995/GAN-TTS#6]
hi，How to calculate the condition_window in dataset.py？ For example, if the sample_rate = 48000，hop_length = 600, what is the condition_window  equals to? I will be looking forward to your reply，thank you.

**Comment by yanggeng1995** [comment]
Hi,  The condition_window only represents the number of frames of acoustic
parameters input to network every training step, no calculation is required.

Kerry0123 <notifications@github.com> 于2020年12月2日周三 上午11:36写道：

**Comment by Kerry0123** [comment]
Hi，samples and conditions in dataset.py are related to  condition_window .  I  modify the parameters，For example：
sample_rate = 48000
n_fft = 2400
fft_bins = n_fft // 2 + 1
num_mels = 80
preemph = 0.97
#frame_length_ms=50
#frame_shift_ms=12.5
hop_length = 600  #frame_shift_ms * sample_rate / 1000
win_length = 2400  #frame_length_ms * sample_rate / 1000
fmin = 95
fmax = 7600
min_level_db = -100
ref_level_db = 20

condition_window = 400
The error information is as follows：

 File "train.py", line 184, in train
    sc_loss, mag_loss = stft_criterion(g_outputs.squeeze(1), samples.squeeze(1))
  File "/nfs/private/yanglu/zhrtvc/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/nfs/project/duanxuhuan/tts_code/normalization_1201GAN-TTS-master/utils/loss.py", line 96, in forward
    sc_loss, mag_loss = layer(fake_signals, true_signals)
  File "/nfs/private/yanglu/zhrtvc/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/nfs/project/duanxuhuan/tts_code/normalization_1201GAN-TTS-master/utils/loss.py", line 76, in forward
    sc_loss = self.sc_loss(predicts_mag, targets_mag)
  File "/nfs/private/yanglu/zhrtvc/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/nfs/project/duanxuhuan/tts_code/normalization_1201GAN-TTS-master/utils/loss.py", line 29, in forward
    x = torch.norm(targets_mag - predicts_mag, p='fro')
RuntimeError: The size of tensor a (2001) must match the size of tensor b (401) at non-singleton dimension 1

debugging，
in dataset.py: 
samples.shape is  torch.Size([32, 1, 240000])
conditions.shape is  torch.Size([32, 80, 400]).
How can I solve it？  I will be looking forward to your reply，thank you.

**Comment by yanggeng1995** [comment]
In fact, GAN-TTS only supports hop_size=120, if you want to adapt to other hop_size, you need to modify this code https://github.com/yanggeng1995/GAN-TTS/blob/4675fa108c4c52f190d27a32a8d9e9ce1c68d7a1/models/generator.py#L15-L23 you need to modify this so that the product of the fourth parameter in GBlock is the hop_size you set. For hop_size=120, the product of [1, 1, 2, 2, 2, 3, 5] is ok. For hop_size=600, may be you can use [1, 2, 2, 2, 3, 5, 5].

**Comment by Kerry0123** [comment]
Oh, I see. Thank you.
